### ISSUE TITLE
Credential script file's eval doesn't work with some commands

### ISSUE THREAD

**Issue by nwalke** [opsidian/awsc#1]
I have a script file in `~/.awsc/myprofile` that looks like this:
```
 #!/bin/bash
 set -euo pipefail

 AWS_PROFILE='myprofile' awsc auth \
     --cache-dir '/Users/nwalke/.awsc' \
     --session-name 'myprofile' \
     --duration-seconds '43200'

 . /Users/nwalke/.awsc/myprofile.env

 eval "$@"
```

Some of the commands I use with this aren't working because of `eval`.  If I change that to `exec` those commands work just fine.

**Comment by bandesz** [comment]
Fixed in https://github.com/opsidian/awsc/releases/tag/0.0.4
